"use server"

// This file is the database layer for the /tasks page.
// Client components can call these exported async functions, but the code in
// this file always runs on the server where it can safely use Prisma.

import { revalidatePath } from "next/cache"

// prisma is our reusable Prisma Client. It knows how to connect to Neon/Postgres.
import { prisma } from "@/lib/prisma"

// These UI types describe the shape of data the React components understand.
import type {
  Task,
  TaskPriority,
  TaskStatus,
} from "@/components/tasks/task-card"

// TaskModel is the raw database row shape generated by Prisma from schema.prisma.
import type { TaskModel } from "@/lib/generated/prisma/models/Task"

// This is the data the add/edit form sends to the server.
// It is smaller than a full Task because the database creates fields like id.
type TaskFormInput = {
  title: string
  description: string
  priority: TaskPriority
  dueDate: string
}

// When a server action changes task data, we revalidate this route so Next.js
// knows the database-backed /tasks page should be refreshed.
const TASKS_PATH = "/tasks"

// Module 7 will add Clerk auth. When that happens, every server action below
// must check the signed-in user and filter/mutate only that user's tasks.

// These maps translate between UI-friendly labels and database enum values.
// The database stores stable uppercase values because enums should be predictable.
// The UI shows readable words because users should not see database-style labels.
const priorityToDb = {
  High: "HIGH",
  Medium: "MEDIUM",
  Low: "LOW",
} as const

// Converts database priority values back into the labels expected by TaskCard.
const priorityFromDb = {
  HIGH: "High",
  MEDIUM: "Medium",
  LOW: "Low",
} as const

// Converts database status values back into the labels expected by TaskCard.
const statusFromDb = {
  TODO: "Todo",
  IN_PROGRESS: "In Progress",
  DONE: "Done",
} as const

// Converts UI status labels into database enum values when updating a task.
const statusToDb = {
  Todo: "TODO",
  "In Progress": "IN_PROGRESS",
  Done: "DONE",
} as const

// Temporary stand-in for real AI. Keeping this on the server means the future
// OpenAI call can replace this function without changing the component much.
function buildTemporaryAiSuggestion(task: TaskFormInput) {
  if (task.priority === "High") {
    return "Start this early and define the first concrete action before doing lower-priority work."
  }

  if (task.priority === "Medium") {
    return "Schedule this after your high-priority work so it keeps moving without taking over the day."
  }

  return "Keep this available as a quick win, but do not let it interrupt higher-impact work."
}

// The form gives us a string, but the database stores dueDate as DateTime.
// Empty string becomes null because due dates are optional in schema.prisma.
function parseDueDate(value: string) {
  if (!value) {
    return null
  }

  // Date inputs submit YYYY-MM-DD. Adding a time avoids timezone parsing surprises.
  return new Date(`${value}T12:00:00`)
}

// The edit form needs the date in YYYY-MM-DD format because that is what
// <input type="date"> expects for its value.
function formatDueDateForInput(value: Date | null) {
  if (!value) {
    return ""
  }

  return value.toISOString().slice(0, 10)
}

// The task card needs a human-readable date, not the raw Date object.
function formatDueDateForDisplay(value: Date | null) {
  if (!value) {
    return "No due date"
  }

  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(value)
}

// Converts a raw Prisma row into the UI Task shape.
// This keeps database details out of the React components.
function mapTaskFromDatabase(task: TaskModel): Task {
  return {
    id: task.id,
    title: task.title,
    description: task.description,
    priority: priorityFromDb[task.priority],
    status: statusFromDb[task.status],
    dueDate: formatDueDateForDisplay(task.dueDate),
    dueDateInput: formatDueDateForInput(task.dueDate),
    aiSuggestion:
      task.aiSuggestion ?? "No AI suggestion has been generated yet.",
  }
}

// Cleans and validates form input before writing it to the database.
// This is server-side validation, so it still runs even if someone bypasses the UI.
function normalizeTaskInput(input: TaskFormInput) {
  const title = input.title.trim()
  const description = input.description.trim()

  if (!title || !description) {
    throw new Error("Task title and description are required.")
  }

  return {
    title,
    description,
    // Convert the UI label into the enum value Postgres stores.
    priority: priorityToDb[input.priority],
    dueDate: parseDueDate(input.dueDate),
    aiSuggestion: buildTemporaryAiSuggestion(input),
  }
}

// Read all tasks from PostgreSQL for the /tasks page.
// This is called by app/tasks/page.tsx before rendering TaskDashboard.
export async function getTasks() {
  const tasks = await prisma.task.findMany({
    orderBy: {
      createdAt: "desc",
    },
  })

  return tasks.map(mapTaskFromDatabase)
}

// Create one database row from the add-task form.
// Returns the newly created task in UI format so the dashboard can update immediately.
export async function createTask(input: TaskFormInput) {
  const task = await prisma.task.create({
    data: normalizeTaskInput(input),
  })

  // Tell Next.js that /tasks has changed because the database changed.
  revalidatePath(TASKS_PATH)

  return mapTaskFromDatabase(task)
}

// Update one existing task by id.
// The id comes from the task card the user chose to edit.
export async function updateTask(taskId: string, input: TaskFormInput) {
  const task = await prisma.task.update({
    where: {
      id: taskId,
    },
    data: normalizeTaskInput(input),
  })

  revalidatePath(TASKS_PATH)

  return mapTaskFromDatabase(task)
}

// Delete one existing task by id.
// This does not return a task because the row no longer exists after deletion.
export async function deleteTask(taskId: string) {
  await prisma.task.delete({
    where: {
      id: taskId,
    },
  })

  revalidatePath(TASKS_PATH)
}

// Complete or reopen a task.
// The UI sends the current status, and the server decides the next status.
export async function toggleTaskComplete(
  taskId: string,
  currentStatus: TaskStatus
) {
  // If it is already done, reopen it as Todo. Otherwise, mark it Done.
  const nextStatus =
    currentStatus === "Done" ? statusToDb.Todo : statusToDb.Done

  const task = await prisma.task.update({
    where: {
      id: taskId,
    },
    data: {
      status: nextStatus,
    },
  })

  revalidatePath(TASKS_PATH)

  return mapTaskFromDatabase(task)
}
