"use server"

// This file is the database layer for the /tasks page.
// Client components can call these exported async functions, but the code in
// this file always runs on the server where it can safely use Prisma.

import { auth } from "@clerk/nextjs/server"
import { revalidatePath } from "next/cache"

// prisma is our reusable Prisma Client. It knows how to connect to Neon/Postgres.
import { prisma } from "@/lib/prisma"

// These UI types describe the shape of data the React components understand.
import type { Task, TaskPriority } from "@/components/tasks/task-card"

// TaskModel is the raw database row shape generated by Prisma from schema.prisma.
import type { TaskModel } from "@/lib/generated/prisma/models/Task"

// This is the data the add/edit form sends to the server.
// It is smaller than a full Task because the database creates fields like id.
type TaskFormInput = {
  title: string
  description: string
  priority: TaskPriority
  priorityReason: string
  dueDate: string
}

// When a server action changes task data, we revalidate this route so Next.js
// knows the database-backed /tasks page should be refreshed.
const TASKS_PATH = "/tasks"

// Authentication proves who made the request. Returning Clerk's userId lets
// each Prisma query also perform authorization by selecting only owned rows.
async function requireSignedInUser() {
  const { userId } = await auth()

  if (!userId) {
    throw new Error("You must be signed in to manage tasks.")
  }

  return userId
}

// These maps translate between UI-friendly labels and database enum values.
// The database stores stable uppercase values because enums should be predictable.
// The UI shows readable words because users should not see database-style labels.
const priorityToDb = {
  High: "HIGH",
  Medium: "MEDIUM",
  Low: "LOW",
} as const

// Converts database priority values back into the labels expected by TaskCard.
const priorityFromDb = {
  HIGH: "High",
  MEDIUM: "Medium",
  LOW: "Low",
} as const

// Converts database status values back into the labels expected by TaskCard.
const statusFromDb = {
  TODO: "Todo",
  IN_PROGRESS: "In Progress",
  DONE: "Done",
} as const

// The form gives us a string, but the database stores dueDate as DateTime.
// Empty string becomes null because due dates are optional in schema.prisma.
function parseDueDate(value: string) {
  if (!value) {
    return null
  }

  // Date inputs submit YYYY-MM-DD. Adding a time avoids timezone parsing surprises.
  return new Date(`${value}T12:00:00`)
}

// The edit form needs the date in YYYY-MM-DD format because that is what
// <input type="date"> expects for its value.
function formatDueDateForInput(value: Date | null) {
  if (!value) {
    return ""
  }

  return value.toISOString().slice(0, 10)
}

// The task card needs a human-readable date, not the raw Date object.
function formatDueDateForDisplay(value: Date | null) {
  if (!value) {
    return "No due date"
  }

  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(value)
}

// Converts a raw Prisma row into the UI Task shape.
// This keeps database details out of the React components.
function mapTaskFromDatabase(task: TaskModel): Task {
  return {
    id: task.id,
    title: task.title,
    description: task.description,
    priority: priorityFromDb[task.priority],
    status: statusFromDb[task.status],
    dueDate: formatDueDateForDisplay(task.dueDate),
    dueDateInput: formatDueDateForInput(task.dueDate),
    priorityReason: task.priorityReason ?? "",
    aiSuggestion: task.aiSuggestion ?? "",
    aiSteps: task.aiSteps,
  }
}

// Cleans and validates form input before writing it to the database.
// This is server-side validation, so it still runs even if someone bypasses the UI.
function normalizeTaskInput(input: TaskFormInput) {
  const title = input.title.trim()
  const description = input.description.trim()
  const priorityReason = input.priorityReason.trim()

  if (!title || !description) {
    throw new Error("Task title and description are required.")
  }

  if (title.length > 120 || description.length > 1000) {
    throw new Error("Task details are too long.")
  }

  if (priorityReason.length > 240) {
    throw new Error("Priority explanations must be 240 characters or less.")
  }

  return {
    title,
    description,
    // Convert the UI label into the enum value Postgres stores.
    priority: priorityToDb[input.priority],
    priorityReason: priorityReason || null,
    dueDate: parseDueDate(input.dueDate),
  }
}

// Read only rows owned by the authenticated Clerk user.
// Filtering in PostgreSQL is safer than fetching every row and filtering in React.
export async function getTasks() {
  const userId = await requireSignedInUser()

  const tasks = await prisma.task.findMany({
    where: {
      userId,
    },
    orderBy: {
      createdAt: "desc",
    },
  })

  return tasks.map(mapTaskFromDatabase)
}

// Create one database row from the add-task form.
// Returns the newly created task in UI format so the dashboard can update immediately.
export async function createTask(input: TaskFormInput) {
  const userId = await requireSignedInUser()

  const task = await prisma.task.create({
    data: {
      ...normalizeTaskInput(input),
      // Ownership comes from the trusted Clerk session, never from browser input.
      userId,
    },
  })

  // Tell Next.js that /tasks has changed because the database changed.
  revalidatePath(TASKS_PATH)

  return mapTaskFromDatabase(task)
}

// Update one existing task by id.
// The id comes from the task card the user chose to edit.
export async function updateTask(taskId: string, input: TaskFormInput) {
  const userId = await requireSignedInUser()

  const task = await prisma.task.update({
    where: {
      id: taskId,
      // Combining id and userId prevents one user from updating another user's row.
      userId,
    },
    data: {
      ...normalizeTaskInput(input),
      // A plan generated from previous task details is no longer trustworthy
      // after an edit. The user can request a fresh plan from the updated card.
      aiSuggestion: null,
      aiSteps: [],
    },
  })

  revalidatePath(TASKS_PATH)

  return mapTaskFromDatabase(task)
}

// Delete one existing task by id.
// This does not return a task because the row no longer exists after deletion.
export async function deleteTask(taskId: string) {
  const userId = await requireSignedInUser()

  await prisma.task.delete({
    where: {
      id: taskId,
      userId,
    },
  })

  revalidatePath(TASKS_PATH)
}

// Complete or reopen a task. The server reads the current value directly from
// PostgreSQL instead of trusting status sent by the browser.
export async function toggleTaskComplete(taskId: string) {
  const userId = await requireSignedInUser()

  const currentTask = await prisma.task.findFirst({
    where: {
      id: taskId,
      userId,
    },
    select: {
      status: true,
    },
  })

  if (!currentTask) {
    throw new Error("Task not found.")
  }

  // Prisma returns the database enum, so the transition is decided from trusted data.
  const nextStatus = currentTask.status === "DONE" ? "TODO" : "DONE"

  const task = await prisma.task.update({
    where: {
      id: taskId,
      userId,
    },
    data: {
      status: nextStatus,
    },
  })

  revalidatePath(TASKS_PATH)

  return mapTaskFromDatabase(task)
}
