"use server"

// This file is the database layer for the /tasks page.
// Client components can call these exported async functions, but the code in
// this file always runs on the server where it can safely use Prisma.

import { auth } from "@clerk/nextjs/server"
import { revalidatePath } from "next/cache"

// prisma is our reusable Prisma Client. It knows how to connect to Neon/Postgres.
import { prisma } from "@/lib/prisma"

// These UI types describe the shape of data the React components understand.
import type { Task } from "@/components/tasks/task-card"
import {
  getUtcDateKey,
  type DailyPlanState,
  type DailyPlanView,
} from "@/lib/daily-plan"

// TaskModel is the raw database row shape generated by Prisma from schema.prisma.
import type { TaskModel } from "@/lib/generated/prisma/models/Task"
import {
  parseTaskDueDate,
  taskFormInputSchema,
  taskIdSchema,
  type TaskFormInput,
} from "@/lib/tasks/task-input"

type TaskActionFailure = {
  success: false
  message: string
  fieldErrors?: Record<string, string[] | undefined>
}

export type TaskMutationActionResult =
  | {
      success: true
      task: Task
    }
  | TaskActionFailure

export type DeleteTaskActionResult =
  | {
      success: true
    }
  | TaskActionFailure

// When a server action changes task data, we revalidate this route so Next.js
// knows the database-backed /tasks page should be refreshed.
const TASKS_PATH = "/tasks"

// Authentication proves who made the request. Returning Clerk's userId lets
// each Prisma query also perform authorization by selecting only owned rows.
async function requireSignedInUser() {
  const { userId } = await auth()

  if (!userId) {
    throw new Error("You must be signed in to manage tasks.")
  }

  return userId
}

async function getSignedInUserId() {
  const { userId } = await auth()
  return userId
}

function persistenceFailure(
  operation: string,
  error: unknown
): TaskActionFailure {
  console.error(`Task ${operation} failed`, error)

  return {
    success: false,
    message: `Could not ${operation} the task. Try again.`,
  }
}

// These maps translate between UI-friendly labels and database enum values.
// The database stores stable uppercase values because enums should be predictable.
// The UI shows readable words because users should not see database-style labels.
const priorityToDb = {
  High: "HIGH",
  Medium: "MEDIUM",
  Low: "LOW",
} as const

// Converts database priority values back into the labels expected by TaskCard.
const priorityFromDb = {
  HIGH: "High",
  MEDIUM: "Medium",
  LOW: "Low",
} as const

// Converts database status values back into the labels expected by TaskCard.
const statusFromDb = {
  TODO: "Todo",
  IN_PROGRESS: "In Progress",
  DONE: "Done",
} as const

// The edit form needs the date in YYYY-MM-DD format because that is what
// <input type="date"> expects for its value.
function formatDueDateForInput(value: Date | null) {
  if (!value) {
    return ""
  }

  return value.toISOString().slice(0, 10)
}

// The task card needs a human-readable date, not the raw Date object.
function formatDueDateForDisplay(value: Date | null) {
  if (!value) {
    return "No due date"
  }

  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(value)
}

// Converts a raw Prisma row into the UI Task shape.
// This keeps database details out of the React components.
function mapTaskFromDatabase(task: TaskModel): Task {
  return {
    id: task.id,
    title: task.title,
    description: task.description,
    priority: priorityFromDb[task.priority],
    status: statusFromDb[task.status],
    dueDate: formatDueDateForDisplay(task.dueDate),
    dueDateInput: formatDueDateForInput(task.dueDate),
    completedAt: task.completedAt?.toISOString() ?? "",
    priorityReason: task.priorityReason ?? "",
    aiSuggestion: task.aiSuggestion ?? "",
    aiSteps: task.aiSteps,
  }
}

// Cleans and validates form input before writing it to the database.
// This is server-side validation, so it still runs even if someone bypasses the UI.
function normalizeTaskInput(input: TaskFormInput) {
  const parsedInput = taskFormInputSchema.parse(input)

  return {
    title: parsedInput.title,
    description: parsedInput.description,
    // Convert the UI label into the enum value Postgres stores.
    priority: priorityToDb[parsedInput.priority],
    priorityReason: parsedInput.priorityReason || null,
    dueDate: parseTaskDueDate(parsedInput.dueDate),
  }
}

// Read only rows owned by the authenticated Clerk user.
// Filtering in PostgreSQL is safer than fetching every row and filtering in React.
export async function getTasks() {
  const userId = await requireSignedInUser()

  const tasks = await prisma.task.findMany({
    where: {
      userId,
    },
    orderBy: {
      createdAt: "desc",
    },
  })

  return tasks.map(mapTaskFromDatabase)
}

// Load the user's current plan and today's separate usage record. A previous
// UTC day's plan can remain visible while the new day's allowance resets.
export async function getDailyPlanState(): Promise<DailyPlanState> {
  const userId = await requireSignedInUser()
  const usageDate = getUtcDateKey()

  const [plan, usage] = await Promise.all([
    prisma.dailyPlan.findUnique({
      where: {
        userId,
      },
      include: {
        items: {
          orderBy: {
            position: "asc",
          },
        },
      },
    }),
    prisma.dailyPlanUsage.findUnique({
      where: {
        userId_usageDate: {
          userId,
          usageDate,
        },
      },
      select: {
        generationCount: true,
      },
    }),
  ])

  const planView: DailyPlanView | null =
    plan && plan.items.length > 0
      ? {
          id: plan.id,
          summary: plan.summary,
          planDate: plan.planDate,
          generatedAt: plan.generatedAt.toISOString(),
          items: plan.items.map((item) => ({
            taskId: item.taskId,
            position: item.position,
            reason: item.reason,
          })),
        }
      : null

  return {
    plan: planView,
    usageDate,
    generationsUsedToday: usage?.generationCount ?? 0,
  }
}

// Create one database row from the add-task form.
// Returns the newly created task in UI format so the dashboard can update immediately.
export async function createTask(
  input: TaskFormInput
): Promise<TaskMutationActionResult> {
  const userId = await getSignedInUserId()

  if (!userId) {
    return {
      success: false,
      message: "You must be signed in to create tasks.",
    }
  }

  const parsedInput = taskFormInputSchema.safeParse(input)

  if (!parsedInput.success) {
    return {
      success: false,
      message: "Check the highlighted task details and try again.",
      fieldErrors: parsedInput.error.flatten().fieldErrors,
    }
  }

  let task: TaskModel

  try {
    task = await prisma.task.create({
      data: {
        ...normalizeTaskInput(parsedInput.data),
        // Ownership comes from the trusted Clerk session, never from browser input.
        userId,
      },
    })
  } catch (error) {
    return persistenceFailure("create", error)
  }

  // Tell Next.js that /tasks has changed because the database changed.
  revalidatePath(TASKS_PATH)

  return { success: true, task: mapTaskFromDatabase(task) }
}

// Update one existing task by id.
// The id comes from the task card the user chose to edit.
export async function updateTask(
  taskId: string,
  input: TaskFormInput
): Promise<TaskMutationActionResult> {
  const userId = await getSignedInUserId()

  if (!userId) {
    return {
      success: false,
      message: "You must be signed in to update tasks.",
    }
  }

  const parsedTaskId = taskIdSchema.safeParse(taskId)
  const parsedInput = taskFormInputSchema.safeParse(input)

  if (!parsedTaskId.success || !parsedInput.success) {
    return {
      success: false,
      message: "Check the highlighted task details and try again.",
      fieldErrors: parsedInput.success
        ? undefined
        : parsedInput.error.flatten().fieldErrors,
    }
  }

  let task: TaskModel

  try {
    task = await prisma.task.update({
      where: {
        id: parsedTaskId.data,
        // Combining id and userId prevents one user from updating another user's row.
        userId,
      },
      data: {
        ...normalizeTaskInput(parsedInput.data),
        // A plan generated from previous task details is no longer trustworthy
        // after an edit. The user can request a fresh plan from the updated card.
        aiSuggestion: null,
        aiSteps: [],
      },
    })
  } catch (error) {
    return persistenceFailure("update", error)
  }

  revalidatePath(TASKS_PATH)

  return { success: true, task: mapTaskFromDatabase(task) }
}

// Delete one existing task by id.
// This does not return a task because the row no longer exists after deletion.
export async function deleteTask(
  taskId: string
): Promise<DeleteTaskActionResult> {
  const userId = await getSignedInUserId()

  if (!userId) {
    return {
      success: false,
      message: "You must be signed in to delete tasks.",
    }
  }

  const parsedTaskId = taskIdSchema.safeParse(taskId)

  if (!parsedTaskId.success) {
    return { success: false, message: "Select a valid task and try again." }
  }

  try {
    await prisma.task.delete({
      where: {
        id: parsedTaskId.data,
        userId,
      },
    })
  } catch (error) {
    return persistenceFailure("delete", error)
  }

  revalidatePath(TASKS_PATH)
  return { success: true }
}

// Complete or reopen a task. The server reads the current value directly from
// PostgreSQL instead of trusting status sent by the browser.
export async function toggleTaskComplete(
  taskId: string
): Promise<TaskMutationActionResult> {
  const userId = await getSignedInUserId()

  if (!userId) {
    return {
      success: false,
      message: "You must be signed in to update tasks.",
    }
  }

  const parsedTaskId = taskIdSchema.safeParse(taskId)

  if (!parsedTaskId.success) {
    return { success: false, message: "Select a valid task and try again." }
  }

  let currentTask: { status: "TODO" | "IN_PROGRESS" | "DONE" } | null

  try {
    currentTask = await prisma.task.findFirst({
      where: {
        id: parsedTaskId.data,
        userId,
      },
      select: {
        status: true,
      },
    })
  } catch (error) {
    return persistenceFailure("update", error)
  }

  if (!currentTask) {
    return {
      success: false,
      message: "Task not found or no longer available.",
    }
  }

  // Prisma returns the database enum, so the transition is decided from trusted data.
  const nextStatus = currentTask.status === "DONE" ? "TODO" : "DONE"

  let task: TaskModel

  try {
    task = await prisma.task.update({
      where: {
        id: parsedTaskId.data,
        userId,
      },
      data: {
        status: nextStatus,
        completedAt: nextStatus === "DONE" ? new Date() : null,
      },
    })
  } catch (error) {
    return persistenceFailure("update", error)
  }

  revalidatePath(TASKS_PATH)

  return { success: true, task: mapTaskFromDatabase(task) }
}
